<?php
/**
 * This file is generated by the "yii asset" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version 2023-03-10 18:54:42
 */
return [
    'app' => [
        'class' => 'an602\\components\\assets\\WebStaticAssetBundle',
        'defer' => false,
        'defaultDepends' => false,
        'basePath' => '@webroot-static',
        'baseUrl' => '@web-static',
        'jsPosition' => 1,
        'js' => [
            'js/an602-app.js',
        ],
        'css' => [
            'css/an602-app.css',
        ],
        'preload' => [
            'js/an602-app.js',
            'css/an602-app.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'defer' => [
        'class' => 'an602\\components\\assets\\WebStaticAssetBundle',
        'defer' => true,
        'jsPosition' => 1,
        'defaultDepends' => false,
        'basePath' => '@webroot-static',
        'baseUrl' => '@web-static',
        'js' => [
            'js/an602-bundle.js',
        ],
        'css' => [],
        'preload' => [
            'js/core-bundle.js',
            'css/core-bundle.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'yii\\web\\JqueryAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app',
        ],
    ],
    'yii\\jui\\JuiAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'app',
        ],
    ],
    'an602\\assets\\JuiBootstrapBridgeAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\jui\\JuiAsset',
            'app',
        ],
    ],
    'yii\\web\\YiiAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'app',
        ],
    ],
    'yii\\widgets\\ActiveFormAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'app',
        ],
    ],
    'yii\\validators\\ValidationAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'app',
        ],
    ],
    'yii\\bootstrap\\BootstrapAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app',
        ],
    ],
    'yii\\bootstrap\\BootstrapPluginAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'an602\\assets\\JuiBootstrapBridgeAsset',
            'app',
        ],
    ],
    'an602\\assets\\BluebirdAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app',
        ],
    ],
    'an602\\assets\\FontAwesomeAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app',
        ],
    ],
    'an602\\assets\\AnimateCssAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app',
        ],
    ],
    'an602\\assets\\OpenSansAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app',
        ],
    ],
    'an602\\assets\\PjaxAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app',
        ],
    ],
    'an602\\assets\\JqueryTimeAgoAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app',
        ],
    ],
    'an602\\assets\\HighlightJsStyleAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app',
        ],
    ],
    'an602\\assets\\NProgressStyleAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app',
        ],
    ],
    'an602\\assets\\Select2StyleAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app',
        ],
    ],
    'an602\\assets\\BlueimpGalleryStyleAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app',
        ],
    ],
    'an602\\assets\\FlatelementsStyleAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app',
        ],
    ],
    'an602\\assets\\IntersectionObserverPolyfillAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app',
        ],
    ],
    'an602\\assets\\CoreApiAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app',
        ],
    ],
    'an602\\modules\\content\\assets\\ContentAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app',
        ],
    ],
    'an602\\modules\\file\\assets\\FileAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app',
        ],
    ],
    'an602\\assets\\AppAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'an602\\assets\\JuiBootstrapBridgeAsset',
            'yii\\jui\\JuiAsset',
            'yii\\web\\YiiAsset',
            'yii\\widgets\\ActiveFormAsset',
            'yii\\validators\\ValidationAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'yii\\bootstrap\\BootstrapPluginAsset',
            'an602\\assets\\BluebirdAsset',
            'an602\\assets\\FontAwesomeAsset',
            'an602\\assets\\AnimateCssAsset',
            'an602\\assets\\OpenSansAsset',
            'an602\\assets\\PjaxAsset',
            'an602\\assets\\JqueryTimeAgoAsset',
            'an602\\assets\\HighlightJsStyleAsset',
            'an602\\assets\\NProgressStyleAsset',
            'an602\\assets\\Select2StyleAsset',
            'an602\\assets\\BlueimpGalleryStyleAsset',
            'an602\\assets\\FlatelementsStyleAsset',
            'an602\\assets\\IntersectionObserverPolyfillAsset',
            'an602\\assets\\CoreApiAsset',
            'an602\\modules\\content\\assets\\ContentAsset',
            'an602\\modules\\file\\assets\\FileAsset',
            'defer',
        ],
    ],
    'an602\\assets\\JqueryHighlightAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'defer',
        ],
    ],
    'an602\\assets\\JqueryAutosizeAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'defer',
        ],
    ],
    'an602\\assets\\Select2Asset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'an602\\assets\\Select2StyleAsset',
            'defer',
        ],
    ],
    'an602\\assets\\JqueryWidgetAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'defer',
        ],
    ],
    'an602\\assets\\NProgressAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'an602\\assets\\NProgressStyleAsset',
            'defer',
        ],
    ],
    'an602\\assets\\JqueryNiceScrollAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'defer',
        ],
    ],
    'an602\\assets\\BlueimpFileUploadAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'an602\\assets\\JqueryWidgetAsset',
            'defer',
        ],
    ],
    'an602\\assets\\BlueimpGalleryAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'an602\\assets\\JqueryWidgetAsset',
            'an602\\assets\\BlueimpGalleryStyleAsset',
            'defer',
        ],
    ],
    'an602\\assets\\ClipboardJsAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'defer',
        ],
    ],
    'an602\\assets\\ImagesLoadedAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'defer',
        ],
    ],
    'an602\\assets\\HighlightJsAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'an602\\assets\\HighlightJsStyleAsset',
            'defer',
        ],
    ],
    'an602\\assets\\SwipedEventsAssets' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'defer',
        ],
    ],
    'an602\\assets\\CoreExtensionAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'defer',
        ],
    ],
    'an602\\assets\\ProsemirrorEditorAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'defer',
        ],
    ],
    'an602\\modules\\content\\assets\\ProseMirrorRichTextAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'an602\\assets\\ProsemirrorEditorAsset',
            'defer',
        ],
    ],
    'an602\\assets\\JqueryCookieAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'defer',
        ],
    ],
    'an602\\modules\\user\\assets\\UserAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'defer',
        ],
    ],
    'an602\\modules\\live\\assets\\LiveAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'defer',
        ],
    ],
    'an602\\modules\\notification\\assets\\NotificationAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'defer',
        ],
    ],
    'an602\\modules\\content\\assets\\ContentContainerAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'defer',
        ],
    ],
    'an602\\modules\\user\\assets\\UserPickerAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'an602\\assets\\Select2Asset',
            'defer',
        ],
    ],
    'an602\\modules\\post\\assets\\PostAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'defer',
        ],
    ],
    'an602\\modules\\space\\assets\\SpaceAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'defer',
        ],
    ],
    'an602\\modules\\topic\\assets\\TopicAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'defer',
        ],
    ],
    'an602\\modules\\ui\\filter\\assets\\FilterAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'an602\\modules\\topic\\assets\\TopicAsset',
            'defer',
        ],
    ],
    'an602\\modules\\comment\\assets\\CommentAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'defer',
        ],
    ],
    'an602\\modules\\like\\assets\\LikeAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'defer',
        ],
    ],
    'an602\\modules\\stream\\assets\\StreamAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'an602\\modules\\content\\assets\\ContentAsset',
            'an602\\modules\\content\\assets\\ContentContainerAsset',
            'an602\\modules\\ui\\filter\\assets\\FilterAsset',
            'an602\\modules\\user\\assets\\UserAsset',
            'an602\\assets\\CoreExtensionAsset',
            'defer',
        ],
    ],
    'an602\\modules\\activity\\assets\\ActivityAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'an602\\modules\\stream\\assets\\StreamAsset',
            'defer',
        ],
    ],
    'an602\\modules\\space\\assets\\SpaceChooserAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'an602\\modules\\space\\assets\\SpaceAsset',
            'an602\\modules\\user\\assets\\UserAsset',
            'defer',
        ],
    ],
];
